<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <DefaultItemExcludes>$(DefaultItemExcludes);KayipEsyaBulmaOtomasyonu/**;KayipEsyaBulma Otomasyonu/**;kayipesyabulmaotomasyonu/**</DefaultItemExcludes>
    <UserSecretsId>3d754a00-72b9-4903-bd1b-2c263d1d9c23</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="KayipEsyaBulmaOtomasyonu/**/*.cs" />
    <Compile Remove="KayipEsyaBulma Otomasyonu/**/*.cs" />
    <Content Remove="KayipEsyaBulmaOtomasyonu/**" />
    <Content Remove="KayipEsyaBulma Otomasyonu/**" />
    <EmbeddedResource Remove="KayipEsyaBulmaOtomasyonu/**" />
    <EmbeddedResource Remove="KayipEsyaBulma Otomasyonu/**" />
    <None Remove="KayipEsyaBulmaOtomasyonu/**" />
    <None Remove="KayipEsyaBulma Otomasyonu/**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FuzzySharp" Version="*" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
  </ItemGroup>

</Project>
